<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="nEXBOX" duration-ms="52165" started-at="2020-01-06T21:06:47Z" finished-at="2020-01-06T21:07:40Z">
    <groups>
    </groups>
    <test name="nEXBOX_TestCase1" duration-ms="52165" started-at="2020-01-06T21:06:47Z" finished-at="2020-01-06T21:07:40Z">
      <class name="com.TestCase.Login_TestCase_Folder.Login_TestCase">
        <test-method status="PASS" signature="Url_Hit()[pri:2, instance:com.TestCase.Login_TestCase_Folder.Login_TestCase@553f17c]" name="Url_Hit" duration-ms="25378" started-at="2020-01-06T21:06:47Z" finished-at="2020-01-06T21:07:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Url_Hit -->
        <test-method status="FAIL" signature="Without_Password()[pri:3, instance:com.TestCase.Login_TestCase_Folder.Login_TestCase@553f17c]" name="Without_Password" duration-ms="11065" started-at="2020-01-06T21:07:13Z" finished-at="2020-01-06T21:07:24Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[WithOut Password Successfully login...== expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: WithOut Password Successfully login...== expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.PageObject.Loginpage.LoginPage.UserName(LoginPage.java:45)
at com.TestCase.Login_TestCase_Folder.Login_TestCase.Without_Password(Login_TestCase.java:15)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Without_Password -->
        <test-method status="FAIL" signature="Without_UserName()[pri:4, instance:com.TestCase.Login_TestCase_Folder.Login_TestCase@553f17c]" name="Without_UserName" duration-ms="8120" started-at="2020-01-06T21:07:24Z" finished-at="2020-01-06T21:07:32Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[WithOut UserName Successfully login...== expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: WithOut UserName Successfully login...== expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.PageObject.Loginpage.LoginPage.Password_Data(LoginPage.java:70)
at com.TestCase.Login_TestCase_Folder.Login_TestCase.Without_UserName(Login_TestCase.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Without_UserName -->
        <test-method status="PASS" signature="With_Username_Password()[pri:5, instance:com.TestCase.Login_TestCase_Folder.Login_TestCase@553f17c]" name="With_Username_Password" duration-ms="7462" started-at="2020-01-06T21:07:32Z" finished-at="2020-01-06T21:07:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- With_Username_Password -->
      </class> <!-- com.TestCase.Login_TestCase_Folder.Login_TestCase -->
    </test> <!-- nEXBOX_TestCase1 -->
  </suite> <!-- nEXBOX -->
</testng-results>
